### ISSUE TITLE
Build issue for --with-java when Java 11 installed

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/homebrew-tap#2]
If Java 11 is installed, the formula won't build if `--with-java` is specified because Ice doesn't support building with Java 11. We could fix the formula to depend on java `1.8` instead of `1.8+`. This would ensure it builds with Java 1.8.

Building with Java 1.8 won't be enough for the IceGridGUI bundled application to work however... to get it to work we also need to fix `ice/java/src/IceGridGUI/build.gradle` to require `com.panayotis:appbundler:1.1.0`, 1.0.2 doesn't support Java > 1.8.

I guess we need to patch the sources and create a new tag to patch v3.7.1?

**Comment by externl** [comment]
We can apply a patch directly in the formula or from a GitHub commit diff.

eg. https://github.com/zeroc-ice/homebrew-tap/blob/master/Formula/ice.rb#L29-L32

EDIT: I think making Java 8 a build time (when using `--with-java`) dependency makes the most sense.

**Comment by externl** [comment]
I updated the ice formula to depend on java `1.8`.

 I think the simplest is to just apply at patch to the end of the file which updates the build dep version. Sound fine?

**Comment by externl** [comment]
We're actually going to remove building the GUI from the formula.

EDIT: We're just going to leave it as it is for now. Users who want the GUI should use the cask.

**Comment by externl** [comment]
Ice 3.7.2 (now released) supports building with Java 11.
