### ISSUE TITLE
symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by devzw** [zeroc-ice/homebrew-tap#5]
make install prefix=/opt/homebrew/Cellar/icetouch@3.6/3.6.4 OPTIMIZE=yes MCP
Last 15 lines from /Users/zhangwei/Library/Logs/Homebrew/icetouch@3.6/01.make:
  "_mcpp_use_mem_buffers", referenced from:
  "_mcpp_use_mem_buffers", referenced from:
      Slice::Preprocessor::preprocess(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
      Slice::Preprocessor::printMakefileDependencies(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, Slice::Preprocessor::Language, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
      Slice::Preprocessor::preprocess(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
      Slice::Preprocessor::printMakefileDependencies(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, Slice::Preprocessor::Language, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../lib/IceTouch/Cpp/bin/slice2cpp] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [../../lib/IceTouch/ObjC/bin/slice2objc] Error 1
make[1]: *** [install] Error 1
make: *** [install] Error 1

**Comment by externl** [comment]
Hi @devzw, what version of macOS & Xcode are you using?

**Comment by devzw** [comment]
> Hi @devzw, what version of macOS & Xcode are you using?

My macos version is 13.5, Xcode version is 14.3.1, MacBook Pro 14，Apple M2 Pro
