### ISSUE TITLE
Can't it be installed in the M2 chip of the Mac

### ISSUE THREAD

**Issue by devzw** [zeroc-ice/homebrew-tap#6]
In Mac OS, computers installed on the M2 pro chip via homebrew software will display the following error message

My macos version is 13.5, Xcode version is 14.3.1, MacBook Pro 14，Apple M2 Pro

brew install zeroc-ice/tap/icetouch@3.6
==> Downloading https://formulae.brew.sh/api/cask.jws.json
-#O#- #   #
==> Downloading https://formulae.brew.sh/api/formula.jws.json
#=#=-#  #
==> Fetching zeroc-ice/tap/icetouch@3.6
==> Cloning https://github.com/zeroc-ice/icetouch.git
Updating /Users/z/Library/Caches/Homebrew/icetouch@3.6--git
==> Checking out tag v3.6.4
HEAD is now at 5f8ab96 Update ice submodule to v3.6.4
HEAD is now at 5f8ab96 Update ice submodule to v3.6.4
Entering 'ice'
/Users/z/Library/Caches/Homebrew/icetouch@3.6--git/ice
==> Installing icetouch@3.6 from zeroc-ice/tap
==> make install prefix=/opt/homebrew/Cellar/icetouch@3.6/3.6.4 OPTIMIZE=yes MCP
Last 15 lines from /Users/z/Library/Logs/Homebrew/icetouch@3.6/01.make:
  "_mcpp_use_mem_buffers", referenced from:
  "_mcpp_use_mem_buffers", referenced from:
      Slice::Preprocessor::preprocess(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
      Slice::Preprocessor::printMakefileDependencies(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, Slice::Preprocessor::Language, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
      Slice::Preprocessor::preprocess(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
      Slice::Preprocessor::printMakefileDependencies(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, Slice::Preprocessor::Language, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in Preprocessor_Slice_cpp.o
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../lib/IceTouch/ObjC/bin/slice2objc] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [../../lib/IceTouch/Cpp/bin/slice2cpp] Error 1
make[1]: *** [install] Error 1
make: *** [install] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/zeroc-ice/homebrew-tap/issues

**Comment by externl** [comment]
HI @devzw,

Ice Touch 3.6 does not support Apple Silicon. It's recommend to upgrade to Ice 3.7. The Ice Touch SDKs were merged into Ice in 3.7.

**Comment by PaulWyw** [comment]
Hi @externl 
I have also encountered the same problem. How can I solve it to install it icetouch@36
thanks

**Comment by externl** [comment]
Hi @PaulWyw, the only "fix" is to upgrade to Ice 3.7 as I mentioned above.
